### PR TITLE
improve Chinese translation && optimize for page display

### PR DESCRIPTION
**Pull request by coder-bts**
for Chinese (Simplified)
Improved a few translations
Shortened a few translations to fit on page display

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank you! 🔥

**Comment by coder-bts** [comment]
@alisalahio of one thing I am unsure... please check this after you merge the PR:

for "100% 正常" (100% Uptime) "常" would go on the next line after "100% 正" when I am debugging on my console, no matter how long the phrase is (if only one character, that character goes to the next line; if more than one, only the last character does)

This issue cannot be repeated when the phrase gets replaced by other languages (e.g. Uptime)

Here are some screenshots for your reference

image
image
image

**Comment by coder-bts** [comment]
@alisalahio I just tried to debug the HTML code on Instatus:

This is the code Instatus currently has, in which the issue would occur
```html
<div class="jsx-1043634912 component-item__status text-ok"><span class="jsx-1043634912 truncate narrow-spacing">100 %</span>&nbsp;正常</div>
```

This is what I tried to do and would resolve the display issue
```html
<div class="jsx-1043634912 component-item__status text-ok"><span class="jsx-1043634912 truncate narrow-spacing">100 %&nbsp;正常</span></div>
```

Being more specific:

Including the phrase inside the `<span></span>` tag. This might be a bit challenging to implement, but it should work; I'm not terribly sure of why this issue occurs.

Hope this helps!

**Comment by alisalahio** [comment]
Hi @coder-bts Thank you so much for your effort! :D I'll work on this tomorrow and send you an update once it's fixed :D

**Comment by coder-bts** [comment]
@alisalahio thank you for being so kind! I will try to keep the translation always updated and would love to help with any other open-source repo by Instatus I could. :D

Also, quick question: do you offer discounts on Pro for contributors ;)

**Comment by alisalahio** [comment]
@coder-bts Thank you! I appreciate your contribution so much! :D 
Would you please send me an email at ali@instatus.com to discuss discounts :D

**Comment by alisalahio** [comment]
Hi @coder-bts I just fixed this issue! WIll be released to all status pages with the next release

Would you please let me know your status page url so that I could release it early for you?

**Comment by coder-bts** [comment]
Sure, it will be https://bitznet.status.page/


Best,
Chihao (Bill) Huang

**Comment by alisalahio** [comment]
Just deployed the update it to your page, Chihao :D

**Comment by coder-bts** [comment]
Well received! Perfectly working!

Best,
Chihao (Bill) Huang

**Pull request merged**
