### PR TITLE
Add ZH-TW support

### PR DESCRIPTION
**Pull request by Mr-Sheep**
Add support for Chinese (Traditional)
May need same fix as mentioned in issue #39

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank you so much! I'll work on issue #39 very soon!

**Comment by alisalahio** [comment]
Hi @Mr-Sheep I just fixed this issue! WIll be released to all status pages with the next release

Would you please let me know your status page url so that I could release it early for you?

**Comment by Mr-Sheep** [comment]
Hi @alisalahio my status page: https://as208884.instatus.com

**Comment by alisalahio** [comment]
Hi @Mr-Sheep Just deployed the fix to your page :D

**Pull request merged**
