### PR TITLE
Add translations to new main status values

### PR DESCRIPTION
**Pull request by AmrIKhudair**

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank youu!
Please make sure that {{component}} is correct all files
It's {{Komponente}} in de.json, and maybe not correct in other files so please re-check

**Comment by AmrIKhudair** [comment]
> Thank youu! Please make sure that {{component}} is correct all files It's {{Komponente}} in de.json, and maybe not correct in other files so please re-check

ok will recheck

**Comment by AmrIKhudair** [comment]
> Thank youu! Please make sure that {{component}} is correct all files It's {{Komponente}} in de.json, and maybe not correct in other files so please re-check

I fixed the one in `de.json` file, then I check them using regular expressions `"\{\{[^c]` and I didn't find anyone else

**Comment by alisalahio** [comment]
There are still other files. Please recheck and let me know when you fix everything.

**Comment by AmrIKhudair** [comment]
> There are still other files. Please recheck and let me know when you fix everything.

I fixed the last one now I'm positive it is correct on all files

**Comment by alisalahio** [comment]
There's still `es.json` :D

**Comment by AmrIKhudair** [comment]
> There's still `es.json` :D

Yes apologies I don't know how couldn't I find it although I used regular expressions. How did you know is there an automatable way to check for this or you just had to check them manually one by one?

**Comment by alisalahio** [comment]
Manual is underrated :D

**Comment by AmrIKhudair** [comment]
> Manual is underrated :D

Ok I will make sure the check them manually one by one in the next times

**Pull request merged**
