### PR TITLE
add Chinese (Simplified) Support

### PR DESCRIPTION
**Pull request by coder-bts**
add Chinese (Simplified) Support

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank you!!! 🥳

**Comment by coder-bts** [comment]
@alisalahio thank you! can't wait to use the translation on my own page!

**Comment by alisalahio** [comment]
You can use it right now 🥳🚀

**Comment by coder-bts** [comment]
@alisalahio much appreciated! BTW I just submitted a new PR to improve a few translations to fit the page display

**Pull request merged**
